import { Dimensions, Platform, StatusBar, StyleSheet } from 'react-native';
import DeviceInfo from 'react-native-device-info';
import { heightPixel, widthPixel } from './helpers';

export const deviceType = Platform.OS;
export const StatusBarHeight = StatusBar.currentHeight;
export const deviceWidth = Dimensions.get('window').width;
export const deviceHeight = Dimensions.get('window').height;

export const appVersion = DeviceInfo.getVersion();
export const buildNumber = DeviceInfo.getBuildNumber();

export const lightColors = {

  primary: '#060606',
  greaytext: '#B9B9B9',
  purple1: '#776CF8',
  purple2: '#3F12A5',
  textfieldcolor: '#F5F5F5',
  livecolor: '#EA4335',
  activetab: '#6DDDE4',
  chipcolor: '#303030',
  inactivetab: '#313131',
  inactivetabicon: '#777777',
  secondary: '#A6F6F2',
  subtitle: '#B9B9B9',
  white: '#ffffff',
  whitish: '#f2f2f2',
  imageview: '#F0F0F0',
  halfWhite: '#f5f5f5',
  black: '#000000',
  blackShade: '#313131',
  gray: '#565656',
  greyE4: '#E4E4E4',
  greishBg: '#EBEBEB',
  iconGrey: '#AAAAAA',
  whiteSmoke: 'rgba(239, 239, 239, 1)',
  greish: '#929292',
  borderGrey: '#E8E8E8',
  textGrey: '#71717A',
  label: '#B2B2B2',
  arrowcolor: '#B9B9B9',
  success: '#19A519',
  successLight: '#53CD53',
  seaGreen: '#55A99D',
  transparent: 'transparent',
  tabBarBackground: '#93939373',
  fbColor: '#3C5A8D',
  blue: '#5971ED',
  highlightedTxt: '#4480FF',
  lightGray: '#F1F1F1',
  userInfoHighlight: '#E5EAF1',
  postBackground: '#F7F7FD',
  disableBtnColor: '#CFD2DE',
  disableeBtnTxt: '#929AB9',
  borderColor: '#F2F2F2',
  seprator: '#E2E2E2',
  pending: '#DA9F32',
  voiceNote: '#EDE7FF',
  inputFieldColor: '#A5A5A52F',
  progressBar: '#D9D9D9',
  textColor: '#64748B',
  danger: '#EC4949',
  danger2: '#EF6F6F',
  red: '#C62837',
  yellow: '#FFD700',
  background: '#F5F5F5',
  redOpacity: 'rgba(255,11,15,0.1)',
};

export const darkColors = {
  backgroundColor:'black',
  primary: '#ffffff',
  greaytext: '#B9B9B9',
  purple1: '#776CF8',
  purple2: '#3F12A5',
  textfieldcolor: '#313131',
  livecolor: '#EA4335',
  activetab: '#6DDDE4',
  chipcolor: '#303030',
  inactivetab: '#313131',
  inactivetabicon: '#777777',
  secondary: '#A6F6F2',
  subtitle: '#B9B9B9',
  white: '#000000',
  whitish: '#0D0D0D',
  imageview: '#313131',
  halfWhite: '#0A0A0A',
  black: '#ffffff',
  blackShade: '#1F1F1F',
  gray: '#A9A9A9',
  greyE4: '#1A1A1A',
  greishBg: '#121212',
  iconGrey: '#555555',
  whiteSmoke: 'rgba(16, 16, 16, 1)',
  greish: '#6D6D6D',
  borderGrey: '#171717',
  textGrey: '#8E8E92',
  label: '#4D4D4D',
  arrowcolor: '#FFFFFF',
  success: '#19A519',
  successLight: '#53CD53',
  seaGreen: '#55A99D',
  transparent: 'transparent',
  tabBarBackground: '#6C6C6C73',
  fbColor: '#3C5A8D',
  blue: '#5971ED',
  highlightedTxt: '#4480FF',
  lightGray: '#1E1E1E',
  userInfoHighlight: '#1A1E24',
  postBackground: '#08080C',
  disableBtnColor: '#302D3C',
  disableeBtnTxt: '#6D7185',
  borderColor: '#0D0D0D',
  seprator: '#1D1D1D',
  pending: '#DA9F32',
  voiceNote: '#221A3B',
  inputFieldColor: '#5A5A5A2F',
  progressBar: '#262626',
  textColor: '#9B9EA4',
  danger: '#EC4949',
  danger2: '#EF6F6F',
  red: '#C62837',
  yellow: '#FFD700',
  background: '#000000',
  redOpacity: 'rgba(255,11,15,0.1)',
};

export const getColors = (isDarkMode: boolean) =>
  isDarkMode ? darkColors : lightColors;

export const getAppStyles = (isDarkMode: boolean) => {
  const themeColors = getColors(isDarkMode);
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: themeColors.background,
    },
    flexrow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    imageBackgroundStyle: {
      width: '100%',
      height: '100%',
      backgroundColor: themeColors.black,
    },
    flexRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    flexRowBetween: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    marginTop: {
      marginTop: deviceType == 'ios' ? heightPixel(10) : 0,
    },
    MARGINTOP: { marginTop: 10 },
    bottombtnContainer: {
      paddingHorizontal: widthPixel(15),
      paddingBottom: deviceType == 'ios' ? heightPixel(30) : heightPixel(20),
    },
    lineSeparator: {
      borderTopWidth: 1,
      marginVertical: 10,
      borderTopColor: themeColors.borderGrey,
    },
    wrapContainer: {
      marginTop: 10,
      flexWrap: 'wrap',
      flexDirection: 'row',
      alignItems: 'center',
    },
    shadow: {
      elevation: 4,
      shadowRadius: 4,
      shadowOpacity: 0.2,
      shadowColor: themeColors.greish,
      shadowOffset: {
        width: 0,
        height: 0,
      },
    },
  });
};

export const fontFamily = {
  Gilroy: {
    regular: 'Gilroy-Regular',
    medium: 'Gilroy-Medium',
    semibold: 'Gilroy-Semibold',
    bold: 'Gilroy-Bold',
  },
};

export const screens = {
  authStack: 'AuthStack',
  mainStack: 'MainStack',
  bottomTabs: 'BottomTabs',
  drawerWithBottomTabs: 'DrawerWithBottomTabs',
  onBoarding: 'OnBoarding',
  InstructorCompleteProfile: 'InstructorCompleteProfile',
  ClassesAuth: 'ClassesAuth',
  Prelogin: 'Prelogin',
  login: 'Login',
  ManageSubscription: 'ManageSubscription',
  signup: 'Signup',
  EditConsultation: 'EditConsultation',
  EditCertification: 'EditCertification',
  forgotPass: 'ForgotPassword',
  resetPass: 'ResetPassword',
  changePass: 'ChangePassword',
  CompleteProfile: 'CompleteProfile',
  EditEmployer: 'EditEmployer',
  Security: 'Security',
  AboutUs: 'AboutUs',
  LanguageScreen: 'LanguageScreen',
  AddProperty: 'AddProperty',
  preference: 'preference',
  otpVerification: 'OtpVerification',
  EditAvailability: 'EditAvailability',
  location: 'location',
  NewProjects: 'NewProjects',
  PropertyDetail: 'PropertyDetail',
  selectRole: 'selectRole',
  EditEducation: 'EditEducation',
  ListedProperty: 'ListedProperty',
  SupportChat: 'SupportChat',
  Splash: 'Splash',
  LearnerHome: 'LearnerHome',
  ContactUs: 'ContactUs',
  AppointmentDetail: 'AppointmentDetail',
  AllSessions: 'AllSessions',
  Classes: 'Classes',
  Allinstructor: 'Allinstructor',
  commentsScreen: 'commentsScreen',
  AppointmentDetailsInstructor: 'AppointmentDetailsInstructor',
  AddEducation: 'AddEducation',
  AddCertifications: 'AddCertifications',
  AddEmployer: 'AddEmployer',
  SelectExpertise: 'SelectExpertise',
  SelectAvailabilityRates: 'SelectAvailabilityRates',
  ConsultationCallType: 'ConsultationCallType',
  AppointmentCompleted: 'AppointmentCompleted',
  BookingRequest: 'BookingRequest',
  AddClass: 'AddClass',
  AddClasses: 'AddClasses',
  EditSession: 'EditSession',
  Sessions: 'Sessions',
  AddSessions: 'AddSessions',
  newThread: 'newThread',
  AllLiveClass: 'AllLiveClass',
  RecordedSession: 'RecordedSession',
  EditProfile: 'EditProfile',
  EditClass: 'EditClass',
  ProfileDetail: 'ProfileDetail',
  LearningOverview: 'LearningOverview',
  MyPayments: 'MyPayments',
  Liveclass: 'Liveclass',
  transactionList: 'transactionList',
  AllRecordingSession: 'AllRecordingSession',
  Search: 'Search',
  Appointment: 'Appointment',
  CompletedSessions: 'CompletedSessions',
  community: 'community',
  JoinedCommunity: 'JoinedCommunity',
  RatingReview: 'RatingReview',
  TopCommunity: 'TopCommunity',
  home: 'Home',
  InstructorHome: 'InstructorHome',
  InstructorProfile: 'InstructorProfile',
  profile: 'Profile',
  session: 'session',
  VideoCall: 'VideoCall',
  checkAvailability: 'checkAvailability',
  AppointmentDetails: 'AppointmentDetails',
  CommunityDetail: 'CommunityDetail',
  PaymentSuccessful: 'PaymentSuccessful',
  WriteReview: 'WriteReview',
  InstructorAppointment: 'InstructorAppointment',
  instructorCommunity: 'instructorCommunity',
  feed: 'Feed',
  more: 'More',
  notifications: 'Notifications',
  faqs: 'FAQs',
  privacyPolicy: 'PrivacyPolicy',
  termsAndConditions: 'Terms&Conditions',
  EditInstructorProfile: 'EditInstructorProfile',
  settings: 'Settings',
  inbox: 'Inbox',
  chat: 'Chat',
  search: 'Search',
  writeReview: 'WriteReview',
  reviews: 'Reviews',
  BookingHistory: 'BookingHistory',
  paymentMethod: 'PaymentMethod',
  favourite: 'Favourite',
  mapScreen: 'MapScreen', // Add mapScreen here
  MyClasses: 'MyClasses',
  support: 'Support',
  Services: 'Services',
};

export const api_urls = {
  base_url: '',
  service_token: '',

  // api's end points
  user: 'user',
  login: 'user/login',
  logout: 'user/logout',
  sociaLogin: 'user/social-login',
  forgotPassword: 'user/send-otp/mail',
  changePassword: 'user/change-password',
  resetPassword: 'user/set-password',
  sendOtp: 'user/send-otp/mail',
  verifyOtpRegister: 'user/verify-otp/register',
  verifyOtpForgotPass: 'user/verify-otp/forgot-password',
  toggleNotification: 'user/toggle-notification',
  uploadAttachment: 'user/upload-attachments',
  post: {
    createPost: 'user/post',
    getPost: 'user/post',
    getPostById: 'post/get-by-id',
    getPostByUserId: 'post/get-by-user-id',
    savePost: 'user/user-saved-post',
    likePost: 'user/like',
    comment: 'user/comment',
    unlockPost: 'user/unlock-post',
    tags: 'user/tag',
    story: 'user/post-user',
    addStoryView: 'user/post-view',
  },
  otherProfile: 'user/other-profile/',
  connections: 'user/get-all-users',
  connect: 'user/user-relationship',
  report: 'user/user-block',
  notifications: {
    get: 'user/notifications',
    unreadCount: 'user/get-unread-count',
    markRead: 'user/mark-single-read',
    markAllRead: 'user/mark-all-read',
  },
  setting: 'user/setting',
  pages: 'user/page',
  faqs: 'user/faq',
};
