export const images = {
  appLogo: require('../assets/images/app-logo.png'),
  appartment: require('../assets/images/appartment.png'),
  appartment1: require('../assets/images/appartment1.png'),
  recentprojects1: require('../assets/images/recentprojects1.png'),
  recentprojects: require('../assets/images/recentprojects.png'),
  recentprojects3: require('../assets/images/recentprojects3.png'),
  recentprojects4: require('../assets/images/recentprojects4.png'),
  recentprojects5: require('../assets/images/recentprojects5.png'),
  backgroundimage: require('../assets/images/background.png'),
  splash: require('../assets/images/splash.png'),
  template: require('../assets/images/template.png'),
  prelogin: require('../assets/images/prelogin.png'),
  appleLogo: require('../assets/images/apple-logo.png'),
  onboarding: require('../assets/images/onboarding.png'),
  googleLogo: require('../assets/images/google-logo.png'),
  noData: require('../assets/images/no-data.png'),
  dummyAvatar: require('../assets/images/dummy-avatar.png'),
  onboarding1: require('../assets/images/onboarding1.png'),
  onboarding2: require('../assets/images/onboarding2.png'),
  onboarding3: require('../assets/images/onboarding3.png'),
  appimage: require('../assets/images/appimage.png'),
  learner: require('../assets/images/learner.png'),
  instructor: require('../assets/images/instructor.png'),
  liveclass: require('../assets/images/liveclass.png'),
  liveicon: require('../assets/images/liveicon.png'),
  recordeddummy: require('../assets/images/recordeddummy.png'),
  recordeddummy1: require('../assets/images/recordeddummy1.png'),
  class: require('../assets/images/class.png'),
  class1: require('../assets/images/class1.png'),
  class2: require('../assets/images/class2.png'),
  allsession: require('../assets/images/allSession.png'),
  allsession1: require('../assets/images/allSession1.png'),
  allsession2: require('../assets/images/allSession2.png'),
  allsession3: require('../assets/images/allSession3.png'),
  recordedsession1: require('../assets/images/recordedsession1.png'),
  recordedsession2: require('../assets/images/recordedsession2.png'),
  recordedsession3: require('../assets/images/recordedsession3.png'),
  recordedsession4: require('../assets/images/recordedsession4.png'),
  recordedsession5: require('../assets/images/recordedsession5.png'),
  recordedsession6: require('../assets/images/recordedsession6.png'),
  userimage: require('../assets/images/userimage.png'),
  videocallimage: require('../assets/images/videocallimage.png'),
  calltab: require('../assets/images/calltab.png'),
  supportimage: require('../assets/images/supportimage.png'),
  subscription: require('../assets/images/subscription.png'),
  subscriptionBanner: require('../assets/images/subscription-banner.png'),
  otpimage: require('../assets/images/otpimage.jpg'),
  changeimage: require('../assets/images/changeimage.jpg'),





  

};

export const icons = {
  germany: require('../assets/icons/germany.png'),

  unheart: require('../assets/icons/unheart.png'),
  darkmode: require('../assets/icons/darkmode.png'),
  lightmode: require('../assets/icons/lightmode.png'),
  share: require('../assets/icons/share.png'),
  play: require('../assets/icons/play.png'),
  album: require('../assets/icons/album.png'),
  box: require('../assets/icons/box.png'),
  map: require('../assets/icons/map.png'),
  bottombar: require('../assets/icons/bottombar.png'),



  recorded: require('../assets/icons/recorded.png'),
  dantal: require('../assets/icons/dantal.png'),
  bed: require('../assets/icons/bed.png'),
  toilet: require('../assets/icons/toilet.png'),
  size: require('../assets/icons/size.png'),
  arrowupright: require('../assets/icons/arrowupright.png'),
  recbutton: require('../assets/icons/recbutton.png'),
  home: require('../assets/icons/home.png'),
  email: require('../assets/icons/email.png'),
  lock: require('../assets/icons/lock.png'),
  notification: require('../assets/icons/notification.png'),
  moon: require('../assets/icons/moon.png'),
  message: require('../assets/icons/message.png'),
  spanish: require('../assets/icons/spanish.png'),
  english: require('../assets/icons/english.png'),
  persian: require('../assets/icons/persian.png'),
  tick: require('../assets/icons/tick.png'),
  verified: require('../assets/icons/verified.png'),
  hand: require('../assets/icons/hand.png'),
  line1: require('../assets/icons/line1.png'),
  ai: require('../assets/icons/ai.png'),
  line2: require('../assets/icons/line2.png'),
  sigarr: require('../assets/icons/sigarr.png'),
  supportlogo: require('../assets/icons/supportlogo.png'),
  motivation: require('../assets/icons/motivation.png'),
  logo: require('../assets/icons/logo.png'),
  blackheart: require('../assets/icons/blackheart.png'),
  calen: require('../assets/icons/calen.png'),
  clock1: require('../assets/icons/clock1.png'),
  book1: require('../assets/icons/book1.png'),
  chart: require('../assets/icons/chart.png'),
  chat: require('../assets/icons/chat.png'),
  info: require('../assets/icons/info.png'),
  sort: require('../assets/icons/sort.png'),
  frescoicon: require('../assets/icons/frescoicon.png'),
  emojiIcon: require('../assets/icons/emoji-icon.png'),
  liveclass: require('../assets/icons/liveclass.png'),
  call: require('../assets/icons/call.png'),
  about: require('../assets/icons/about.png'),
  security: require('../assets/icons/security.png'),
  language: require('../assets/icons/language.png'),
  listedproperty: require('../assets/icons/listedproperty.png'),
  chatappicon: require('../assets/icons/chatappicon.png'),

  



  // tick: require('../assets/icons/tick.png'),
  book: require('../assets/icons/book.png'),
  infoicon: require('../assets/icons/Infoicon.png'),
  next: require('../assets/icons/next.png'),
  bin: require('../assets/icons/bin.png'),
  arrowDown: require('../assets/icons/arrowDown.png'),
  binmodal: require('../assets/icons/binmodal.png'),
  edit: require('../assets/icons/edit.png'),
  key: require('../assets/icons/key.png'),
  bellicon: require('../assets/icons/bellicon.png'),
  heart: require('../assets/icons/heart.png'),
  otheruser: require('../assets/icons/otheruser.png'),
  stars: require('../assets/icons/stars.png'),
  unfilledstar: require('../assets/icons/unfilledstar.png'),
  microphone: require('../assets/icons/microphone.png'),
  disablespeaker: require('../assets/icons/disablespeaker.png'),
  decline: require('../assets/icons/decline.png'),
  disablevideo: require('../assets/icons/disablevideo.png'),
  mute: require('../assets/icons/mute.png'),
  speaker: require('../assets/icons/speaker.png'),
  successicon: require('../assets/icons/successicon.png'),
  modalclose: require('../assets/icons/modalclose.png'),
  videocall: require('../assets/icons/videocall.png'),
  audiocall: require('../assets/icons/audiocall.png'),
  favouritelogo: require('../assets/icons/favouritelogo.png'),
  unfavourite: require('../assets/icons/unfavourite.png'),
  round: require('../assets/icons/round.png'),
  unfilled: require('../assets/icons/unfilled.png'),
  certificate1: require('../assets/icons/certificate1.png'),
  certificate2: require('../assets/icons/certificate2.png'),
  certificate3: require('../assets/icons/certificate3.png'),
  deletebin: require('../assets/icons/deletebin.png'),
  debit: require('../assets/icons/debit.png'),
  stripe: require('../assets/icons/stripe.png'),
  location: require('../assets/icons/location.png'),
  like: require('../assets/icons/like.png'),
  dropdown: require('../assets/icons/dropdown.png'),
  drawer: require('../assets/icons/drawer.png'),
  clip: require('../assets/icons/clip.png'),
  unlike: require('../assets/icons/unlike.png'),
  appIcon: require('../assets/icons/app-icon.jpg'),
  sendicon: require('../assets/icons/sendicon.png'),
  send: require('../assets/icons/sendicon.png'),
  attach: require('../assets/icons/clip.png'),
  close: require('../assets/icons/modalclose.png'),
  star: require('../assets/icons/star.png'),
  rightarrow: require('../assets/icons/rightarrow.png'),
  crown: require('../assets/icons/crown.png'),
  livesession: require('../assets/icons/livesession.jpg'),
  livesession1: require('../assets/icons/livesession1.jpg'),
  dummyAvatar1: require('../assets/icons/dummyAvatar1.png'),
  dummyAvatar2: require('../assets/icons/dummyAvatar2.png'),
  dummyAvatar3: require('../assets/icons/dummyAvatar3.png'),
  dummyAvatar4: require('../assets/icons/dummyAvatar4.png'),
  searchtab: require('../assets/icons/searchtab.png'),
  profiletab: require('../assets/icons/profiletab.png'),
  hometab: require('../assets/icons/hometab.png'),
  communitytab: require('../assets/icons/communitytab.png'),
  appointmenttab: require('../assets/icons/appointmenttab.png'),
  videocalluser: require('../assets/icons/videocalluser.png'),
  add: require('../assets/icons/add.png'),
  upload: require('../assets/icons/add.png'), // Using add icon as upload for now
  calendar: require('../assets/icons/calendar.png'),
  check: require('../assets/icons/check.png'),
  notify: require('../assets/icons/notify.png'),
  cross: require('../assets/icons/cross.png'),
  backArrow: require('../assets/icons/back-arrow.png'),
  camera: require('../assets/icons/camera.png'),
  cameraIcon2: require('../assets/icons/camera-icon-2.png'),
  galleryIcon: require('../assets/icons/gallery-icon.png'),
  logout: require('../assets/icons/logout.png'),
  eyeOpen: require('../assets/icons/eye-open.png'),
  eyeClose: require('../assets/icons/eye-close.png'),
  selected: require('../assets/icons/selected.png'),
  clock: require('../assets/icons/clock.png'),
  video: require('../assets/icons/video.png'),
  filledvideo: require('../assets/icons/filledvideo.png'),
  filter: require('../assets/icons/filter.png'),
  favourite: require('../assets/icons/favourite.png'),
  faqs: require('../assets/icons/faqs.png'),
  support: require('../assets/icons/support.png'),
  termcondition: require('../assets/icons/termcondition.png'),
  privacypolicy: require('../assets/icons/privacypolicy.png'),
  managesubscription: require('../assets/icons/managesubscription.png'),
  paymentmethod: require('../assets/icons/paymentmethod.png'),
  profiledrawer: require('../assets/icons/profiledrawer.png'),
  bookingdrawer: require('../assets/icons/bookingdrawer.png'),
  notificationIcon: require('../assets/icons/notify.png'),
  locationIcon: require('../assets/icons/back-arrow.png'),
  // message: require('../assets/icons/sendicon.png'),
  checkmark: require('../assets/icons/check.png'),
  uncheckedIcon: require('../assets/icons/cross.png'),
  plus: require('../assets/icons/plus.png'),
  report: require('../assets/icons/report.png'),
  comment: require('../assets/icons/comment.png'),
  community1: require('../assets/icons/community1.png'),
  community2: require('../assets/icons/community2.png'),
  community3: require('../assets/icons/community3.png'),
  community4: require('../assets/icons/community4.png'),
  community5: require('../assets/icons/community5.png'),
  jcommunity1: require('../assets/icons/jcommunity1.png'),
  jcommunity2: require('../assets/icons/jcommunity2.png'),
  jcommunity3: require('../assets/icons/jcommunity3.png'),
  jcommunity4: require('../assets/icons/jcommunity4.png'),
  jcommunity5: require('../assets/icons/jcommunity5.png'),
  supportchat: require('../assets/icons/supportchat.png'),
  supportemail: require('../assets/icons/supportemail.png'),
  mark: require('../assets/icons/mark.png'),
  unmark: require('../assets/icons/unmark.png'),
  sessioncount: require('../assets/icons/sessioncount.png'),
  ratingcount: require('../assets/icons/ratingcount.png'),
  appointmentcount: require('../assets/icons/appointmentcount.png'),
  bookingrequest: require('../assets/icons/bookingrequest.png'),
  setting: require('../assets/icons/setting.png'),
  pen: require('../assets/icons/pen.png'),
  zigzac: require('../assets/icons/zigzac.png'),
  filledfavourite: require('../assets/icons/filledfavourite.png'),
  unfilledhome: require('../assets/icons/unfilledhome.png'),
  filledlocation: require('../assets/icons/filledlocation.png'),
  filleduser: require('../assets/icons/filleduser.png'),
  user: require('../assets/icons/user.png'),
  appartment: require('../assets/icons/appartment.png'),
  villas: require('../assets/icons/villas.png'),
  resorts: require('../assets/icons/resorts.png'),
  gradientuser: require('../assets/icons/gradientuser.png'),
  gradientcalendar: require('../assets/icons/gradientCalendar.png'),
  gradientcall: require('../assets/icons/gradientcall.png'),
  gradientlocation: require('../assets/icons/gradientlocation.png'),
  deleteicon: require('../assets/icons/deleteicon.png'),
  cloud: require('../assets/icons/add.png'),






  


};
