export const strings = {
  invalidEmail: 'Invalid email address!',
  invalidPhone: 'Invalid phone number!',
  enterName: 'Please enter your name!',
  selectGender: 'Please select your gender!',
  interests: 'Please add your interests!',
  profileImage: 'Please upload your profile image!',
  selectLanguage: 'Please select your language!',
  enterEmail: 'Please enter your email address!',
  enterPassword: 'Please enter your password!',
  enterConfirmPassword: 'Confirm your password!',
  passwordMismatch: "Password and Confirm Password didn't match!",
  postAddedSuccessfully: 'Post added successfully!',
  propertyAddedSuccessfully: 'Property listed successfully.',
  propertyDeletedSuccessfully: 'Property deleted successfully.',
  propertyUpdatedSuccessfully: 'Property updated successfully.',
  enterPropertyTitle: 'Please enter the property title.',
  enterPropertyAddress: 'Please pick the location on the map for the address.',
  userLogin: 'User Login Successfully',
  signupSuccess: 'Account created successfully.',
  storyAddedSuccessfully: 'Story added successfully!',
  resetPassword:
  'Your password has been reset successfully. Please login to continue.',
  passwordPattern:
    'Password must contain atleast 8 characters with minimum of one capital letter, number and special character.',
  emailDuplication:
    'The given email address already exists! Please try another.',
  phoneDuplication:
    'The given phone number already exists! Please try another.',
  otpVerifiedSuccessfully: 'Otp verified successfully',
  otpVerifiedLoginToContinue:
    'Otp verified successfully. Please login to continue.',
  accountAlreadyRegistered:
    'Account already registered with this email address.',
  accountDeleteSuccess: 'Your account has been deleted successfully.',
  passwordChangedSuccess: 'Your password has been updated successfully.',
  agreeToTerms: 'Please agree to our terms & conditions!',
  reportingComment: 'Please write a comment, why are you reporting this?',
  postReportedSuccess: 'Post reported successfully.',
  storyReportedSuccess: 'Story reported successfully.',
  postDeleteSuccess: 'Post deleted successfully.',
  somethingWentWrong: 'Something went wrong! Please try again later.',
  noInternet: 'No Internet connection found!',
  noNotificationsFound: 'No notifications found!',
  noBlockedUsersFound: 'No blocked users found!',
  noFriendsYet: 'No friends yet!',
  noFriendsFound: 'No friends found!',
  noFollowingsFound: 'No followings found!',
  noPostFound: 'No posts yet!',
  noSuggestionsFound: 'No suggestions found!',
  pleaseTypeMessage: 'Please type a message!',
  noChatFound: 'No chat found!',
  noDataFound: 'No data found!',
  cantSendMessages: "You can't send messages to this conversation!",
  accountDeactivated: 'This account has been deactivated.',
  profileUpdated: 'Profile has been updated successfully.',
  accountPrivacyUpdated: 'Account privacy has been updated successfully.',
  requestAccepted: 'Follower added successfully.',
  requestRejected: 'Request removed successfully.',
  followerRemoved: 'Follower removed successfully.',
  followRequestSent: 'Follow request sent.',
  followRequestCancelled: 'Follow request cancelled.',
  postDescriptionRequired: 'Post description is required!',
  mediaFilesLimit: 'You can select a maximum of 10 media files.',
  postUpdated: 'Post has been updated successfully.',
  commentRequired: 'Please enter a comment!',
  contactMsgSuccess: 'Your message has been sent successfully.',
  emptyFeed:
    'Navigate to the map and follow other users to see their activity.',
  verifyYourEmail:
    "We've sent you a verification email. Kindly confirm your email address and proceed with logging in to continue.",
  selectParticipants: 'Please select participants!',
  emailOrPhoneNotVerified:
    'Your email or mobile number is not verified. Please check your inbox to continue.',
};
